package main

import "fmt"

func main() {
	division(100, 10)
	division(200, 25)
	division(34, 0)
	division(124, 8)
}

func division(dividend, divisor int) {
	defer func() {
		// Con la funci√≥n recover nos podemos recuperar de un p√°nico.
		// Esta funci√≥n devuelve un valor, que nos permite a nosotros saber si en efecto se gener√≥ un p√°nico
		if r := recover(); r != nil {
			fmt.Println("Me recuper√© del p√°nico üòÆ‚Äçüí®")
		}
	}()

	validateZero(divisor)
	fmt.Println(dividend / divisor)
}

func validateZero(divisor int) {
	if divisor == 0 {
		panic("ü§ï No puedes dividir por cero.")
		// Cuando ocurre un p√°nico, el programa se detiene y GO nos otorgar√° la traza
		// Pero nosotros podemos recuperarnos de un p√°nico (ver l√≠nea 14)
	}
}
